-- Connect to Oracle as c##belwin user and run these commands:

-- Create EMPLOYEES table
CREATE TABLE EMPLOYEES (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100),
    ROLE VARCHAR2(50),
    PHONENUMBER NUMBER
);

-- Clear existing data
DELETE FROM EMPLOYEES;
COMMIT;

-- Insert sample data (ID will be auto-generated)
INSERT INTO EMPLOYEES (NAME, EMAIL, ROLE, PHONENUMBER) VALUES ('John Smith', 'john@company.com', 'Developer', 1234567890);
INSERT INTO EMPLOYEES (NAME, EMAIL, ROLE, PHONENUMBER) VALUES ('Sarah Johnson', 'sarah@company.com', 'Manager', 1234567891);
INSERT INTO EMPLOYEES (NAME, EMAIL, ROLE, PHONENUMBER) VALUES ('Michael Brown', 'michael@company.com', 'Analyst', 1234567892);

COMMIT;

-- Verify data
SELECT * FROM EMPLOYEES;