// <auto-generated />
using BlazorProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace BlazorProject.Migrations.OracleDb
{
    [DbContext(typeof(OracleDbContext))]
    [Migration("20251211122304_newer")]
    partial class newer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorProject.Data.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NAME");

                    b.Property<long?>("PhoneNumber")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("PHONENUMBER");

                    b.Property<string>("email")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("role")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ROLE");

                    b.HasKey("Id");

                    b.ToTable("DETAILS");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "John Smith"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sarah Johnson"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Michael Brown"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
